y: 1
floorWorld: world

customWeaponEnabled: false
autoCreateCustomWeapon: false

worldUsage: REUSE

database:
  type: mysql
  host: localhost
  port: 3306
  user: root
  pass: pass
  db: dungeon_tower